services:
  mongo:
    image: mongo:8
    container_name: cafe-rewards-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - cafe_rewards_mongo_data:/data/db

volumes:
  cafe_rewards_mongo_data: